apiVersion: v1
kind: Secret
metadata:
  name: net-core-docker-sample-appsettings
type: Opaque
stringData:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "Connection": "Server=sql-server-service;Database=NetCoreSample;User Id=sa;Password=sa@@2020;MultipleActiveResultSets=true"
      }
    }